# Generated by Django 5.1.4 on 2024-12-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovesPokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moves_pokemons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_1', models.CharField(blank=True, max_length=255, null=True)),
                ('type_2', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mega_evolves', models.IntegerField(blank=True, null=True)),
                ('evolves', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonsDos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'db_table': 'pokemons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovesDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
