# Generated by Django 5.1.4 on 2024-12-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('description', models.TextField()),
                ('moves', models.ManyToManyField(related_name='pokemonsDesc', to='miApi.movedesc')),
            ],
        ),
        migrations.DeleteModel(
            name='MovesDos',
        ),
        migrations.DeleteModel(
            name='PokemonsDos',
        ),
    ]
