# Generated by Django 5.1.4 on 2024-12-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApi', '0002_movedesc_pokemondesc_delete_movesdos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemondesc',
            name='pokedex_number',
        ),
        migrations.AlterField(
            model_name='pokemondesc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
