# Generated by Django 5.1.4 on 2024-12-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApi', '0003_remove_pokemondesc_pokedex_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movedesc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemondesc',
            options={'managed': False},
        ),
    ]
