# Generated by Django 5.1.4 on 2024-12-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApi', '0004_alter_movedesc_options_alter_pokemondesc_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movedesc',
            table='moves',
        ),
        migrations.AlterModelTable(
            name='pokemondesc',
            table='pokemons',
        ),
    ]
